# SITE CONFIGURATION
baseurl: #"/Type-on-Strap"
url: "https://Animadversio.github.io"

# THEME-SPECIFIC CONFIGURATION
title: The mind palace of Binxu                                    # site's title
description: "Binxu's personal blog site for neuroscience and machine learning"      # used by search engines
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Binxu's log book for neuroscience, machine learning and life  # Change Blog header text
header_feature_image: assets/img/header/triangular.jpeg # assets/img/pexels/Galaxy.jpg
header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics: UA-125498144-1                        # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 12
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/'
  # permalink: '/blogs/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'
  # Optional, the default tag to use, omit to disable
  tag: ''
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

# paginate: 8
# paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  tech_note:
    output: true
    permalink: /:collection/:name
  academic_notes:
    output: true
    permalink: /:collection/:name
collection_paginate_path: "collection/page:num"

category-list: [courses, mathematics, neuroscience, machine learning, algorithm, computer science]
tech-cat-list: [coding, machine learning, neuroscience, misc]

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate-v2, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
